name: Pr basics demo

on:
    workflow_dispatch:
    # pull_request:
    #     types: [opened, synchronize, closed]

jobs:
    activity-check:
        runs-on: ubuntu-latest
        steps:
            - name: Print the action name
              run: echo "This event was created by action ${{ github.event }}"